# Generated by Django 2.1 on 2018-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('shop_id', models.TextField()),
                ('shop_name', models.TextField()),
                ('shop_image', models.FileField(upload_to='shops')),
                ('location', models.TextField()),
                ('shop_type', models.TextField()),
                ('description', models.TextField()),
                ('open_hour', models.IntegerField()),
                ('close_hour', models.IntegerField()),
            ],
        ),
    ]
