# Generated by Django 2.1 on 2018-09-26 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('item_name', models.TextField()),
                ('item_image', models.FileField(upload_to='users')),
                ('price', models.IntegerField()),
                ('no_of_stocks', models.IntegerField()),
                ('shop_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('shop_id', models.TextField()),
                ('shop_name', models.TextField()),
                ('shop_image', models.FileField(upload_to='shops')),
                ('location', models.TextField()),
                ('shop_type', models.TextField()),
                ('description', models.TextField()),
                ('open_hour', models.IntegerField()),
                ('close_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('user_image', models.FileField(upload_to='users')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('password', models.TextField()),
                ('register_type', models.TextField()),
                ('google_id', models.CharField(blank=True, max_length=50)),
                ('facebook_id', models.IntegerField()),
            ],
        ),
    ]
