# Generated by Django 2.1 on 2018-09-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopedia_customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
