# Generated by Django 2.1 on 2018-09-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopedia_customer', '0002_delete_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('shop_id', models.TextField()),
                ('shop_name', models.TextField()),
                ('shop_image', models.FileField(upload_to='shops')),
                ('location', models.TextField()),
                ('shop_type', models.TextField()),
                ('description', models.TextField()),
                ('open_hour', models.IntegerField()),
                ('close_hour', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
    ]
