# Generated by Django 2.1 on 2018-09-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopedia_customer', '0003_auto_20180920_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Shops',
        ),
    ]
