# Generated by Django 2.1 on 2018-09-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopedia_customer', '0004_auto_20180920_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('user_image', models.FileField(upload_to='users')),
                ('phone_number', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
